replicaCount: 1

image:
  repository: yadyedida/health-check
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: null
  

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}
tolerations: []
affinity: {}
