apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      containers:
      - name: health-check
        image: yadyedida/health-check:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub-secret  # Reference to the created secret for Docker Hub authentication
