[tool.poetry]
name = "ng_utils"
version = "0.1.0"
description = "A utility package"
authors = ["Author <author@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
# Add any other dependencies here

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
