name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    # paths:
    #   - ./.github/workflows/docker-publish.yml
    #   - ./health_check/Dockerfile
    #   - ./health_check/*.py
    #   - ./health_check/poetry.lock

env:
  REPO_NAME: yadyedida
  IMAGE_NAME: health-check

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prd

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker Buildx (optional, but recommended for advanced builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Build, tag, and push the Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./health_check
        push: true
        tags: |
          ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}_${{ github.sha }}
